### ISSUE TITLE
Change check.yml `on`

### ISSUE THREAD

**Issue by owenpearson** [ably-labs/test-observability-action#8]
Should be like this (as we have done elsewhere):
```yml
on:
  pull_request:
  push:
    branches:
      - main
```
